project_name: ingress-dashboard
before:
  hooks:
    - mkdir -p build-temp
    - sh -c 'sed "s|IMAGE_TO_REPLACE|ghcr.io/reddec/{{ .ProjectName }}:{{ .Tag }}|g"  ingress-dashboard.yaml > build-temp/ingress-dashboard.yaml'
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - arm64
      - amd64
    main: ./cmd/ingress-dashboard
release:
  extra_files:
    - glob: build-temp/ingress-dashboard.yaml

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
dockers:
  - image_templates:
      - "ghcr.io/reddec/{{ .ProjectName }}:{{ .Version }}-amd64"
    use: buildx
    dockerfile: Dockerfile.release
    build_flag_templates:
      - "--platform=linux/amd64"
  - image_templates:
      - "ghcr.io/reddec/{{ .ProjectName }}:{{ .Version }}-arm64v8"
    use: buildx
    goarch: arm64
    dockerfile: Dockerfile.release
    build_flag_templates:
      - "--platform=linux/arm64/v8"
docker_manifests:
  - name_template: "ghcr.io/reddec/{{ .ProjectName }}:{{ .Version }}"
    image_templates:
      - "ghcr.io/reddec/{{ .ProjectName }}:{{ .Version }}-amd64"
      - "ghcr.io/reddec/{{ .ProjectName }}:{{ .Version }}-arm64v8"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
